### ISSUE TITLE
Implement Djikstra Algorithm

### ISSUE THREAD

**Issue by munish7771** [munish7771/Standalone_Programs#2]
Add the code for python/scala implementation of Djikstra algorithm.

**Comment by ShubhayuB** [comment]
Can I work on this?
Also, which folder should I add it in?

**Comment by ShubhayuB** [comment]
Python

**Comment by ShubhayuB** [comment]
So I should explain Djikstra's algorithm in the beginning (Using comments), followed by a demo code right?
